[package]
name = "pbkdf2-identifier"
version = "0.1.0"
authors = ["zer0x64 <dugre.philippe@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.7.1"
sha2 = "0.8.0"

[dev-dependencies]
base64 = "0.11.0"