name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Lib
      run: cd pbkdf2-identifier && cargo build --verbose
    - name: Run Lib Tests
      run: cd pbkdf2-identifier && cargo test --features parallel --verbose
    - name: Build CLI
      run: cd pbkdf2-identifier-cli && cargo build --verbose
    - name: Run CLI Tests
      run: cd pbkdf2-identifier-cli && cargo test --verbose
